# fly.toml app configuration file generated for phonebook-backend-damp-bird-8989 on 2024-07-14T23:13:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-damp-bird-8989'
primary_region = 'bos'

[build]

[env]
PORT = "5173"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
